name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main # Ensure this matches your primary branch (main or master)

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read # Allow read access for checkout and build
  pages: write   # Allow write access to the Pages site
  id-token: write # Allow identity token generation for the deploy action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (if you use them as submodules)
          fetch-depth: 0    # Fetch all history for .GitInfo

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5 # Use actions/configure-pages@v5 or later

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2 # Use actions-hugo@v2 or later
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build Hugo site
        env:
          HUGO_ENV: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3 # Use actions/upload-pages-artifact@v3 or later
        with:
          path: ./public # This is the directory Hugo outputs to

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job completing successfully
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Use actions/deploy-pages@v4 or later
