name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main # Change this to main if your primary branch is 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use actions/checkout@v4 or later
        with:
          submodules: true  # Fetch Hugo themes (if you use them as submodules)
          fetch-depth: 0    # Fetch all history for .GitInfo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2 # Use actions-hugo@v2 or later
        with:
          hugo-version: 'latest' # Or a specific version like '0.121.0'
          # extended: true # Uncomment if you use Hugo extended version features (like SCSS)

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Use actions-gh-pages@v3 or later
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # This is the directory Hugo outputs to
          publish_branch: master # Change this to main if your GitHub Pages serves from 'main' branch root
          # cname: your-custom-domain.com # Uncomment and replace if you use a custom domain
